name: Deploy CineNow

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Descarga el código de CineNow
      - name: Descargar repositorio
        uses: actions/checkout@v4

      # Instala Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Instala las dependencias
      - name: Instalar dependencias
        run: npm ci

      # Construye CineNow con Vite
      - name: Construir proyecto
        run: npm run build

      # Configura GitHub Pages
      - name: Configurar Pages
        uses: actions/configure-pages@v5

      # Prepara la carpeta dist
      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      # Publica CineNow
      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
